[package]
name = "kingmaker"
version = "0.1.0"
edition = "2024"
authors = ["Chance Addis <chance.h.addis@proton.me>"]
description = "A modular, performant, social choice framework for the simulation, computation, and analysis of strategic voting."
keywords = [
    "voting",
    "social-choice",
    "simulation",
    "strategic-voting",
    "game-theory",
]
categories = ["mathematics", "science", "simulation"]
readme = "README.md"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Approximately-Equal/kingmaker"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
ordered-float = { version = "5.0.0", features = ["serde"] }
rand = "0.9.1"
rayon = "1.10.0"
thiserror = "2.0.11"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
criterion = "0.5.1"

[profile.release]
lto = true
codegen-units = 1

[lib]
name = "kingmaker"
path = "src/lib.rs"

[[bin]]
name = "kingmaker"
path = "src/main.rs"

[[bench]]
name = "preferences"
path = "benches/preferences.rs"
harness = false

[[bench]]
name = "tactics"
path = "benches/tactics.rs"
harness = false

[[bench]]
name = "methods"
path = "benches/methods.rs"
harness = false

[[bench]]
name = "elections"
path = "benches/elections.rs"
harness = false
